name: End to End Tests

on:

  schedule:
    - cron: '*/15 * * * *'

jobs:

  e2e:
    name: End to end test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: echo running e2e tests...
